# Generated by Django 4.2.28 on 2026-02-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amazon", "0003_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="product", name="rating", field=models.FloatField(default=0),
        ),
    ]
