# Generated by Django 4.2.28 on 2026-02-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amazon", "0005_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order", name="total_price", field=models.FloatField(),
        ),
    ]
